

USE ROLE ACCOUNTADMIN;

DROP ROLE GLUE_DEMO_ROLE;
DROP USER GLUE_DEMO_USER;


show roles;
show users;

-- create role
CREATE OR REPLACE ROLE GLUE_DEMO_ROLE;

--permission to the role 
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE GLUE_DEMO_ROLE;
GRANT USAGE ON DATABASE GLUE_DATA TO ROLE GLUE_DEMO_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE GLUE_DATA TO ROLE GLUE_DEMO_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE GLUE_DATA TO ROLE GLUE_DEMO_ROLE;

GRANT SELECT, INSERT ON ALL TABLES IN DATABASE GLUE_DATA TO ROLE GLUE_DEMO_ROLE;
GRANT SELECT, INSERT ON FUTURE TABLES IN DATABASE GLUE_DATA TO ROLE GLUE_DEMO_ROLE;


--create user
CREATE OR REPLACE USER GLUE_DEMO_USER
PASSWORD = '****************'
DEFAULT_ROLE = GLUE_DEMO_ROLE
DEFAULT_WAREHOUSE = COMPUTE_WH
MUST_CHANGE_PASSWORD = FALSE;

--assign role to the user 
GRANT ROLE GLUE_DEMO_ROLE TO USER GLUE_DEMO_USER;